# Generated by Django 4.1.1 on 2023-05-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='componetValue',
            new_name='componentValue',
        ),
    ]
